name = "ym-productions"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.production]
name = "ym-productions-prod"
routes = [
  {pattern = "ymproductions.com", zone_name = "ymproductions.com"},
  {pattern = "www.ymproductions.com", zone_name = "ymproductions.com"}
]

[build]
command = "echo 'No build step needed'"
cwd = "./"
watch_paths = []
